/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PostPuma/model/DeletePost_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



DeletePost_request::DeletePost_request()
{
    m_Trash = false;
    m_TrashIsSet = false;
}

DeletePost_request::~DeletePost_request()
{
}

void DeletePost_request::validate()
{
    // TODO: implement validation
}

web::json::value DeletePost_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TrashIsSet)
    {
        val[utility::conversions::to_string_t(U("trash"))] = ModelBase::toJson(m_Trash);
    }

    return val;
}

bool DeletePost_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("trash"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("trash")));
        if(!fieldValue.is_null())
        {
            bool refVal_setTrash;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTrash);
            setTrash(refVal_setTrash);
        }
    }
    return ok;
}

void DeletePost_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TrashIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("trash")), m_Trash));
    }
}

bool DeletePost_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("trash"))))
    {
        bool refVal_setTrash;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("trash"))), refVal_setTrash );
        setTrash(refVal_setTrash);
    }
    return ok;
}

bool DeletePost_request::isTrash() const
{
    return m_Trash;
}

void DeletePost_request::setTrash(bool value)
{
    m_Trash = value;
    m_TrashIsSet = true;
}

bool DeletePost_request::trashIsSet() const
{
    return m_TrashIsSet;
}

void DeletePost_request::unsetTrash()
{
    m_TrashIsSet = false;
}
}
}
}
}


