/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PostPuma/model/DeletePosts_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


void DeletePosts_200_response::validate()
{
    // TODO: implement validation
}

const DeletePosts_200_response::VariantType& DeletePosts_200_response::getVariant() const
{
    return m_variantValue;
}

void DeletePosts_200_response::setVariant(DeletePosts_200_response::VariantType value)
{
    m_variantValue = value;
}

web::json::value DeletePosts_200_response::toJson() const
{
    web::json::value val = web::json::value::object();

    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
            val = web::json::value::null();
        } else {
            val = arg.toJson();
        }
    }, m_variantValue);

    return val;
}

void DeletePosts_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (!std::is_same_v<T, std::monostate>) {
          arg.toMultipart(multipart, prefix);
        }
    }, m_variantValue);
}

template bool DeletePosts_200_response::fromJson<DeletePosts_200_response_oneOf>(const web::json::value& json);
template bool DeletePosts_200_response::fromMultiPart<DeletePosts_200_response_oneOf>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool DeletePosts_200_response::fromJson<DeletePosts_200_response_oneOf_1>(const web::json::value& json);
template bool DeletePosts_200_response::fromMultiPart<DeletePosts_200_response_oneOf_1>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);


}
}
}
}


