/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PostPuma/model/Tag.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Tag::Tag()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Uuid = utility::conversions::to_string_t("");
    m_UuidIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Hex_color = utility::conversions::to_string_t("");
    m_Hex_colorIsSet = false;
}

Tag::~Tag()
{
}

void Tag::validate()
{
    // TODO: implement validation
}

web::json::value Tag::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_UuidIsSet)
    {
        val[utility::conversions::to_string_t(U("uuid"))] = ModelBase::toJson(m_Uuid);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Hex_colorIsSet)
    {
        val[utility::conversions::to_string_t(U("hex_color"))] = ModelBase::toJson(m_Hex_color);
    }

    return val;
}

bool Tag::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("uuid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uuid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUuid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUuid);
            setUuid(refVal_setUuid);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("hex_color"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("hex_color")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHexColor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHexColor);
            setHexColor(refVal_setHexColor);
        }
    }
    return ok;
}

void Tag::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_UuidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uuid")), m_Uuid));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_Hex_colorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("hex_color")), m_Hex_color));
    }
}

bool Tag::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("uuid"))))
    {
        utility::string_t refVal_setUuid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uuid"))), refVal_setUuid );
        setUuid(refVal_setUuid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("hex_color"))))
    {
        utility::string_t refVal_setHexColor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("hex_color"))), refVal_setHexColor );
        setHexColor(refVal_setHexColor);
    }
    return ok;
}

int32_t Tag::getId() const
{
    return m_Id;
}

void Tag::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Tag::idIsSet() const
{
    return m_IdIsSet;
}

void Tag::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Tag::getUuid() const
{
    return m_Uuid;
}

void Tag::setUuid(const utility::string_t& value)
{
    m_Uuid = value;
    m_UuidIsSet = true;
}

bool Tag::uuidIsSet() const
{
    return m_UuidIsSet;
}

void Tag::unsetUuid()
{
    m_UuidIsSet = false;
}
utility::string_t Tag::getName() const
{
    return m_Name;
}

void Tag::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Tag::nameIsSet() const
{
    return m_NameIsSet;
}

void Tag::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Tag::getHexColor() const
{
    return m_Hex_color;
}

void Tag::setHexColor(const utility::string_t& value)
{
    m_Hex_color = value;
    m_Hex_colorIsSet = true;
}

bool Tag::hexColorIsSet() const
{
    return m_Hex_colorIsSet;
}

void Tag::unsetHex_color()
{
    m_Hex_colorIsSet = false;
}
}
}
}
}


