/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PostPuma/model/Version_options_mastodon.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Version_options_mastodon::Version_options_mastodon()
{
    m_Sensitive = false;
    m_SensitiveIsSet = false;
}

Version_options_mastodon::~Version_options_mastodon()
{
}

void Version_options_mastodon::validate()
{
    // TODO: implement validation
}

web::json::value Version_options_mastodon::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_SensitiveIsSet)
    {
        val[utility::conversions::to_string_t(U("sensitive"))] = ModelBase::toJson(m_Sensitive);
    }

    return val;
}

bool Version_options_mastodon::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("sensitive"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("sensitive")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSensitive;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSensitive);
            setSensitive(refVal_setSensitive);
        }
    }
    return ok;
}

void Version_options_mastodon::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_SensitiveIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("sensitive")), m_Sensitive));
    }
}

bool Version_options_mastodon::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("sensitive"))))
    {
        bool refVal_setSensitive;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("sensitive"))), refVal_setSensitive );
        setSensitive(refVal_setSensitive);
    }
    return ok;
}

bool Version_options_mastodon::isSensitive() const
{
    return m_Sensitive;
}

void Version_options_mastodon::setSensitive(bool value)
{
    m_Sensitive = value;
    m_SensitiveIsSet = true;
}

bool Version_options_mastodon::sensitiveIsSet() const
{
    return m_SensitiveIsSet;
}

void Version_options_mastodon::unsetSensitive()
{
    m_SensitiveIsSet = false;
}
}
}
}
}


