/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PostPuma/model/Version_options_pinterest_boards.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Version_options_pinterest_boards::Version_options_pinterest_boards()
{
    m_Accounts_0 = utility::conversions::to_string_t("");
    m_Accounts_0IsSet = false;
}

Version_options_pinterest_boards::~Version_options_pinterest_boards()
{
}

void Version_options_pinterest_boards::validate()
{
    // TODO: implement validation
}

web::json::value Version_options_pinterest_boards::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Accounts_0IsSet)
    {
        val[utility::conversions::to_string_t(U("accounts-0"))] = ModelBase::toJson(m_Accounts_0);
    }

    return val;
}

bool Version_options_pinterest_boards::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("accounts-0"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("accounts-0")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAccounts0;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccounts0);
            setAccounts0(refVal_setAccounts0);
        }
    }
    return ok;
}

void Version_options_pinterest_boards::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Accounts_0IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("accounts-0")), m_Accounts_0));
    }
}

bool Version_options_pinterest_boards::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("accounts-0"))))
    {
        utility::string_t refVal_setAccounts0;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("accounts-0"))), refVal_setAccounts0 );
        setAccounts0(refVal_setAccounts0);
    }
    return ok;
}

utility::string_t Version_options_pinterest_boards::getAccounts0() const
{
    return m_Accounts_0;
}

void Version_options_pinterest_boards::setAccounts0(const utility::string_t& value)
{
    m_Accounts_0 = value;
    m_Accounts_0IsSet = true;
}

bool Version_options_pinterest_boards::accounts0IsSet() const
{
    return m_Accounts_0IsSet;
}

void Version_options_pinterest_boards::unsetAccounts_0()
{
    m_Accounts_0IsSet = false;
}
}
}
}
}


