/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PostPuma/model/Version_options_linkedin.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Version_options_linkedin::Version_options_linkedin()
{
    m_Visibility = utility::conversions::to_string_t("");
    m_VisibilityIsSet = false;
}

Version_options_linkedin::~Version_options_linkedin()
{
}

void Version_options_linkedin::validate()
{
    // TODO: implement validation
}

web::json::value Version_options_linkedin::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_VisibilityIsSet)
    {
        val[utility::conversions::to_string_t(U("visibility"))] = ModelBase::toJson(m_Visibility);
    }

    return val;
}

bool Version_options_linkedin::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("visibility"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("visibility")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVisibility;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVisibility);
            setVisibility(refVal_setVisibility);
        }
    }
    return ok;
}

void Version_options_linkedin::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_VisibilityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("visibility")), m_Visibility));
    }
}

bool Version_options_linkedin::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("visibility"))))
    {
        utility::string_t refVal_setVisibility;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("visibility"))), refVal_setVisibility );
        setVisibility(refVal_setVisibility);
    }
    return ok;
}

utility::string_t Version_options_linkedin::getVisibility() const
{
    return m_Visibility;
}

void Version_options_linkedin::setVisibility(const utility::string_t& value)
{
    m_Visibility = value;
    m_VisibilityIsSet = true;
}

bool Version_options_linkedin::visibilityIsSet() const
{
    return m_VisibilityIsSet;
}

void Version_options_linkedin::unsetVisibility()
{
    m_VisibilityIsSet = false;
}
}
}
}
}


