/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccountsApi.h
 *
 * 
 */

#ifndef POSTPUMA_AccountsApi_H_
#define POSTPUMA_AccountsApi_H_



#include "PostPuma/ApiClient.h"

#include "PostPuma/model/Account.h"
#include "PostPuma/model/ListAccounts_200_response.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace PostPuma {

using namespace org::openapitools::client::model;



class  AccountsApi 
{
public:

    explicit AccountsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~AccountsApi();

    /// <summary>
    /// Get account
    /// </summary>
    /// <remarks>
    /// Get account
    /// </remarks>
    /// <param name="accountUuid">Account UUID</param>
    pplx::task<std::shared_ptr<Account>> getAccount(
        utility::string_t accountUuid
    ) const;
    /// <summary>
    /// List accounts
    /// </summary>
    /// <remarks>
    /// List accounts
    /// </remarks>
    pplx::task<std::shared_ptr<ListAccounts_200_response>> listAccounts(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}

#endif /* POSTPUMA_AccountsApi_H_ */

