/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeletePosts_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_200_response_H_

#include <variant>

#include "PostPuma/ModelBase.h"

#include "PostPuma/model/DeletePosts_200_response_oneOf_1.h"
#include "PostPuma/model/DeletePosts_200_response_oneOf.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  DeletePosts_200_response
{
public:
    DeletePosts_200_response() = default;
    ~DeletePosts_200_response() = default;

    /////////////////////////////////////////////

    void validate();

    web::json::value toJson() const;

    template<typename Target>
    bool fromJson(const web::json::value& json) {
        // convert json to Target type
        Target target;
        if (!target.fromJson(json)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const;

    template<typename Target>
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) {
        // convert multipart to Target type
        Target target;
        if (!target.fromMultiPart(multipart, namePrefix)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    /////////////////////////////////////////////
    /// DeletePosts_200_response members

    using VariantType = std::variant<DeletePosts_200_response_oneOf, DeletePosts_200_response_oneOf_1>;

    const VariantType& getVariant() const;
    void setVariant(VariantType value);

protected:
    VariantType m_variantValue;
};



}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_200_response_H_ */
