/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeletePosts_200_response_oneOf_1.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_200_response_oneOf_1_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_200_response_oneOf_1_H_


#include "PostPuma/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  DeletePosts_200_response_oneOf_1
    : public ModelBase
{
public:
    DeletePosts_200_response_oneOf_1();
    virtual ~DeletePosts_200_response_oneOf_1();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DeletePosts_200_response_oneOf_1 members

    /// <summary>
    /// 
    /// </summary>
    bool isToTrash() const;
    bool toTrashIsSet() const;
    void unsetTo_trash();

    void setToTrash(bool value);


protected:
    bool m_To_trash;
    bool m_To_trashIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_200_response_oneOf_1_H_ */
