/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeletePost_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePost_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePost_request_H_


#include "PostPuma/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  DeletePost_request
    : public ModelBase
{
public:
    DeletePost_request();
    virtual ~DeletePost_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DeletePost_request members

    /// <summary>
    /// Whether to move items to trash or not.
    /// </summary>
    bool isTrash() const;
    bool trashIsSet() const;
    void unsetTrash();

    void setTrash(bool value);


protected:
    bool m_Trash;
    bool m_TrashIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePost_request_H_ */
