/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeleteMediaFiles_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeleteMediaFiles_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeleteMediaFiles_request_H_


#include "PostPuma/ModelBase.h"

#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  DeleteMediaFiles_request
    : public ModelBase
{
public:
    DeleteMediaFiles_request();
    virtual ~DeleteMediaFiles_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DeleteMediaFiles_request members

    /// <summary>
    /// File IDs
    /// </summary>
    std::vector<int32_t>& getItems();
    bool itemsIsSet() const;
    void unsetItems();

    void setItems(std::vector<int32_t> value);


protected:
    std::vector<int32_t> m_Items;
    bool m_ItemsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeleteMediaFiles_request_H_ */
