/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeletePosts_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_request_H_


#include "PostPuma/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  DeletePosts_request
    : public ModelBase
{
public:
    DeletePosts_request();
    virtual ~DeletePosts_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DeletePosts_request members

    /// <summary>
    /// Post UUIDs
    /// </summary>
    std::vector<utility::string_t>& getPosts();
    bool postsIsSet() const;
    void unsetPosts();

    void setPosts(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    bool isTrash() const;
    bool trashIsSet() const;
    void unsetTrash();

    void setTrash(bool value);


protected:
    std::vector<utility::string_t> m_Posts;
    bool m_PostsIsSet;
    bool m_Trash;
    bool m_TrashIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeletePosts_request_H_ */
