/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ListTags_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ListTags_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ListTags_200_response_H_


#include "PostPuma/ModelBase.h"

#include "PostPuma/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  ListTags_200_response
    : public ModelBase
{
public:
    ListTags_200_response();
    virtual ~ListTags_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ListTags_200_response members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AnyType> getData() const;
    bool dataIsSet() const;
    void unsetData();

    void setData(const std::shared_ptr<AnyType>& value);


protected:
    std::shared_ptr<AnyType> m_Data;
    bool m_DataIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ListTags_200_response_H_ */
