/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QueuePost_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_QueuePost_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_QueuePost_200_response_H_


#include "PostPuma/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  QueuePost_200_response
    : public ModelBase
{
public:
    QueuePost_200_response();
    virtual ~QueuePost_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// QueuePost_200_response members

    /// <summary>
    /// 
    /// </summary>
    bool isSuccess() const;
    bool successIsSet() const;
    void unsetSuccess();

    void setSuccess(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getScheduledAt() const;
    bool scheduledAtIsSet() const;
    void unsetScheduled_at();

    void setScheduledAt(const utility::string_t& value);


protected:
    bool m_Success;
    bool m_SuccessIsSet;
    utility::string_t m_Scheduled_at;
    bool m_Scheduled_atIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_QueuePost_200_response_H_ */
