/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Version_options_pinterest_boards.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_pinterest_boards_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_pinterest_boards_H_


#include "PostPuma/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  Version_options_pinterest_boards
    : public ModelBase
{
public:
    Version_options_pinterest_boards();
    virtual ~Version_options_pinterest_boards();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Version_options_pinterest_boards members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAccounts0() const;
    bool accounts0IsSet() const;
    void unsetAccounts_0();

    void setAccounts0(const utility::string_t& value);


protected:
    utility::string_t m_Accounts_0;
    bool m_Accounts_0IsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_pinterest_boards_H_ */
