/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Version_options_pinterest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_pinterest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_pinterest_H_


#include "PostPuma/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "PostPuma/model/Version_options_pinterest_boards.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Version_options_pinterest_boards;


/// <summary>
/// 
/// </summary>
class  Version_options_pinterest
    : public ModelBase
{
public:
    Version_options_pinterest();
    virtual ~Version_options_pinterest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Version_options_pinterest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();

    void setTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLink() const;
    bool linkIsSet() const;
    void unsetLink();

    void setLink(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_pinterest_boards> getBoards() const;
    bool boardsIsSet() const;
    void unsetBoards();

    void setBoards(const std::shared_ptr<Version_options_pinterest_boards>& value);


protected:
    utility::string_t m_Title;
    bool m_TitleIsSet;
    utility::string_t m_Link;
    bool m_LinkIsSet;
    std::shared_ptr<Version_options_pinterest_boards> m_Boards;
    bool m_BoardsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_pinterest_H_ */
