/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Version_options_tiktok_privacy_level.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_tiktok_privacy_level_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_tiktok_privacy_level_H_


#include "PostPuma/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  Version_options_tiktok_privacy_level
    : public ModelBase
{
public:
    Version_options_tiktok_privacy_level();
    virtual ~Version_options_tiktok_privacy_level();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Version_options_tiktok_privacy_level members

    /// <summary>
    /// 
    /// </summary>
    bool isAccount0() const;
    bool account0IsSet() const;
    void unsetAccount_0();

    void setAccount0(bool value);


protected:
    bool m_Account_0;
    bool m_Account_0IsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_tiktok_privacy_level_H_ */
