/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Version_options_tiktok.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_tiktok_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_tiktok_H_


#include "PostPuma/ModelBase.h"

#include "PostPuma/model/Version_options_tiktok_privacy_level.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Version_options_tiktok_privacy_level;


/// <summary>
/// 
/// </summary>
class  Version_options_tiktok
    : public ModelBase
{
public:
    Version_options_tiktok();
    virtual ~Version_options_tiktok();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Version_options_tiktok members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getPrivacyLevel() const;
    bool privacyLevelIsSet() const;
    void unsetPrivacy_level();

    void setPrivacyLevel(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getAllowComments() const;
    bool allowCommentsIsSet() const;
    void unsetAllow_comments();

    void setAllowComments(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getAllowDuet() const;
    bool allowDuetIsSet() const;
    void unsetAllow_duet();

    void setAllowDuet(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getAllowStitch() const;
    bool allowStitchIsSet() const;
    void unsetAllow_stitch();

    void setAllowStitch(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getContentDisclosure() const;
    bool contentDisclosureIsSet() const;
    void unsetContent_disclosure();

    void setContentDisclosure(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getBrandOrganicToggle() const;
    bool brandOrganicToggleIsSet() const;
    void unsetBrand_organic_toggle();

    void setBrandOrganicToggle(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Version_options_tiktok_privacy_level> getBrandContentToggle() const;
    bool brandContentToggleIsSet() const;
    void unsetBrand_content_toggle();

    void setBrandContentToggle(const std::shared_ptr<Version_options_tiktok_privacy_level>& value);


protected:
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Privacy_level;
    bool m_Privacy_levelIsSet;
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Allow_comments;
    bool m_Allow_commentsIsSet;
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Allow_duet;
    bool m_Allow_duetIsSet;
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Allow_stitch;
    bool m_Allow_stitchIsSet;
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Content_disclosure;
    bool m_Content_disclosureIsSet;
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Brand_organic_toggle;
    bool m_Brand_organic_toggleIsSet;
    std::shared_ptr<Version_options_tiktok_privacy_level> m_Brand_content_toggle;
    bool m_Brand_content_toggleIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Version_options_tiktok_H_ */
